import type { AppLanguage } from "../store/preferencesStore";

const content = {
  uk: {
    nav: {
      home: "Головна",
      booking: "Запис",
      account: "Мій запис",
      language: "UA",
      themeLight: "Світла",
      themeDark: "Темна",
      themeSwitchLight: "Світла тема",
      themeSwitchDark: "Темна тема",
    },
    home: {
      badge: "Київ / BarberBook Studio",
      title: "Чіткий онлайн-запис, помітний сервіс і особистий кабінет для керування візитом.",
      description:
        "Оберіть послугу, майстра та зручний час. Якщо плани зміняться, перенесіть або скасуйте запис через персональний кабінет без зайвих дзвінків.",
      primary: "Записатися",
      secondary: "Кабінет",
      call: "Подзвонити",
      servicesLabel: "Послуги",
      servicesTitle: "Оберіть формат візиту, який вам підходить",
      servicesCta: "Почати запис",
      serviceFallback: "Преміальний сервіс без поспіху та з акуратним результатом.",
      select: "Обрати",
      barbersLabel: "Майстри",
      barbersTitle: "Оберіть майстра впевнено",
      barberFallback: "Чисті форми, спокійний сервіс і увага до деталей.",
      policiesLabel: "Правила",
      faqLabel: "Питання",
      visitUs: "Контакти",
      openingHours: "Графік",
      portalLabel: "Особистий кабінет",
      portalTitle: "Керуйте записом окремо від форми бронювання",
      portalText:
        "У кабінеті можна відкрити останні записи, перейти до керування за персональним кодом та швидко скасувати або перенести візит.",
      portalButton: "Відкрити кабінет",
    },
    booking: {
      badge: "Онлайн-запис",
      title: "Створіть запис за чотири кроки",
      reset: "Очистити вибір",
      step1Loading: "Завантажуємо послуги...",
      step1DescriptionFallback: "Класична послуга догляду.",
      step1Selected: "Обрано",
      step1Choose: "Обрати послугу",
      step2Loading: "Завантажуємо майстрів...",
      step2Fallback: "Досвідчений майстер, який працює точно та комфортно.",
      step2Selected: "Обрано",
      step2Choose: "Обрати майстра",
      dateLabel: "Дата",
      slotsTitle: "Доступний час",
      slotsDescription: "Показуємо слоти з урахуванням тривалості послуги та графіка майстра.",
      slotsLoading: "Завантажуємо вільний час...",
      slotsEmpty:
        "На обрану дату немає вільних слотів. Якщо це сьогодні, робочий час міг уже завершитися.",
      contactTitle: "Контактні дані",
      contactDescription:
        "Додайте Telegram, і бот зможе надіслати нагадування та оновлення по запису.",
      placeholderName: "Ім'я",
      placeholderPhone: "Телефон",
      placeholderTelegram: "Telegram, наприклад @yourname",
      placeholderNotes: "Коментар до запису",
      telegramHint:
        "Спершу відкрийте Telegram-бота, а потім зможете користуватися командами для записів.",
      managementHint:
        "Після оплати ви отримаєте персональне посилання для переносу або скасування запису.",
      invalidTelegram: "Вкажіть коректний Telegram username",
      submit: "Перейти до оплати",
      submitting: "Резервуємо слот...",
      submitError: "Не вдалося зарезервувати слот. Спробуйте інший час.",
    },
    checkout: {
      badge: "Оплата запису",
      loading: "Готуємо сторінку оплати...",
      notFound: "Резерв не знайдено.",
      title: "Завершіть депозит, щоб підтвердити запис",
      description:
        "Ми тимчасово утримуємо обраний слот. Після успішної оплати запис підтвердиться автоматично.",
      expiresAt: "Резерв діє до",
      status: "Статус резерву",
      paymentStatus: "Статус платежу",
      depositLabel: "До оплати зараз",
      totalLabel: "Повна вартість",
      mockNote:
        "У цій збірці використовується mock-оплата: кнопка нижче симулює успішний платіжний провайдер і запускає той самий webhook-flow.",
      preparing: "Створюємо checkout-сесію...",
      checkoutError: "Не вдалося підготувати оплату. Спробуйте ще раз.",
      paymentError: "Не вдалося завершити оплату.",
      processing: "Обробляємо оплату...",
      payAction: "Сплатити депозит",
      retryPayment: "Підготувати оплату ще раз",
      retry: "Обрати інший час",
      expiredTitle: "Час резерву минув",
      expiredText: "Слот більше не утримується. Оберіть інший час і створіть новий резерв.",
      nextLabel: "Що далі",
      nextTitle: "Після оплати ми підтвердимо візит автоматично",
      nextText:
        "Сторінка сама перейде до фінального підтвердження, щойно webhook завершить обробку платежу.",
      stepOne: "1. Система створює hold і checkout для вашого слота.",
      stepTwo: "2. Після успішної оплати webhook фіксує платіж у backend.",
      stepThree: "3. Лише потім створюється фінальний booking з персональним доступом.",
    },
    account: {
      badge: "Мій запис",
      title: "Особистий кабінет клієнта",
      description:
        "Тут можна швидко відкрити останні записи або перейти до керування за номером запису та персональним токеном.",
      recent: "Останні записи",
      noRecent: "Ще немає збережених записів. Після оформлення вони з'являться тут автоматично.",
      openBooking: "Відкрити запис",
      removeBooking: "Прибрати",
      manualTitle: "Відкрити за даними запису",
      manualDescription:
        "Вставте номер запису та персональний токен з листа або сторінки підтвердження.",
      bookingId: "Номер запису",
      token: "Персональний токен",
      open: "Відкрити кабінет",
      helper:
        "Після відкриття запису ви зможете перенести або скасувати візит, якщо він ще активний.",
    },
    confirmation: {
      loading: "Завантажуємо запис...",
      incompleteTitle: "Посилання на запис неповне",
      incompleteText:
        "Відкрийте повне посилання зі сторінки підтвердження або попросіть салон повторно надіслати доступ.",
      backHome: "На головну",
      notFound: "Запис не знайдено.",
      accessLabel: "Доступ до запису",
      title: "Деталі вашого візиту",
      status: "Статус",
      client: "Клієнт",
      phone: "Телефон",
      barber: "Майстер",
      service: "Послуга",
      start: "Початок",
      end: "Завершення",
      created: "Створено",
      justNow: "щойно",
      cancelReason: "Причина скасування",
      call: "Подзвонити в салон",
      portal: "Відкрити кабінет",
      selfServiceLabel: "Самообслуговування",
      selfServiceTitle: "Перенесіть або скасуйте запис",
      selfServiceText:
        "Через цей персональний доступ можна змінити лише час, залишаючи ту саму послугу та майстра.",
      cancelTitle: "Скасувати запис",
      cancelPlaceholder: "Необов'язкова причина",
      cancelError: "Зараз не вдалося скасувати запис.",
      cancelPending: "Скасовуємо...",
      cancelAction: "Скасувати запис",
      rescheduleTitle: "Перенести запис",
      slotsLoading: "Завантажуємо слоти...",
      slotsEmpty: "На обрану дату немає альтернативного часу.",
      rescheduleError: "Не вдалося перенести запис на цей час.",
      reschedulePending: "Зберігаємо...",
      rescheduleAction: "Підтвердити новий час",
      closedText: "Для цього запису самообслуговування вже недоступне.",
      contactsLabel: "Контакти",
      telegram: "Відкрити Telegram",
      accountSaved: "Доступ до цього запису збережено у вашому кабінеті.",
    },
    status: {
      pending: "Очікує підтвердження",
      confirmed: "Підтверджено",
      canceled: "Скасовано",
      completed: "Завершено",
    },
    holdStatus: {
      created: "Створено",
      payment_pending: "Очікує на оплату",
      paid: "Оплачено, підтверджуємо",
      converted: "Підтверджено",
      expired: "Термін резерву минув",
      released: "Резерв знято",
      failed: "Оплата не вдалася",
    },
    paymentStatus: {
      unpaid: "Не оплачено",
      partially_paid: "Частково оплачено",
      pending: "В очікуванні",
      paid: "Оплачено",
      failed: "Помилка",
      refunded: "Повернено",
      partial_refund: "Часткове повернення",
    },
    shop: {
      city: "Київ",
      hours: [
        { label: "Пн-Пт", value: "09:00-20:00" },
        { label: "Сб", value: "10:00-18:00" },
        { label: "Нд", value: "Лише за графіком" },
      ],
      highlights: [
        "Актуальні слоти за графіком майстрів і тривалістю послуг",
        "Швидкий запис без реєстрації з опціональними Telegram-нагадуваннями",
        "Простий перенос або скасування через особистий кабінет",
      ],
      policies: [
        "Безкоштовне перенесення або скасування не пізніше ніж за 2 години до візиту.",
        "Якщо запізнюєтесь, напишіть нам у Telegram і ми спробуємо притримати час.",
        "На бороду та комбо-послуги краще приходити на 5 хвилин раніше.",
      ],
      faq: [
        {
          question: "Чи можна записатися без реєстрації?",
          answer: "Так. Достатньо імені та телефону, а Telegram можна додати за бажанням.",
        },
        {
          question: "Як працюють нагадування?",
          answer: "Якщо додасте свій Telegram username і запустите бота, ми зможемо надсилати нагадування й оновлення.",
        },
        {
          question: "Чи можна змінити майстра пізніше?",
          answer: "Особистий кабінет змінює час для того самого майстра та послуги. Для ширших змін краще звернутися в салон.",
        },
      ],
    },
  },
  en: {
    nav: {
      home: "Home",
      booking: "Booking",
      account: "My booking",
      language: "EN",
      themeLight: "Light",
      themeDark: "Dark",
      themeSwitchLight: "Light theme",
      themeSwitchDark: "Dark theme",
    },
    home: {
      badge: "Kyiv / BarberBook Studio",
      title: "Sharp online booking, stronger visuals, and a personal cabinet to manage your visit.",
      description:
        "Choose the service, the barber, and the best time slot. If plans change later, reschedule or cancel from your personal cabinet without extra calls.",
      primary: "Book now",
      secondary: "My booking",
      call: "Call us",
      servicesLabel: "Services",
      servicesTitle: "Choose the visit format that fits your day",
      servicesCta: "Start booking",
      serviceFallback: "Premium chair time with a calm pace and a polished finish.",
      select: "Select",
      barbersLabel: "Barbers",
      barbersTitle: "Choose your barber with confidence",
      barberFallback: "Clean technique, calm service, and strong attention to detail.",
      policiesLabel: "Policies",
      faqLabel: "FAQ",
      visitUs: "Visit us",
      openingHours: "Opening hours",
      portalLabel: "Client cabinet",
      portalTitle: "Manage appointments outside the booking flow",
      portalText:
        "The cabinet gives quick access to recent bookings, manual access by personal token, and fast cancel or reschedule actions.",
      portalButton: "Open cabinet",
    },
    booking: {
      badge: "Online booking",
      title: "Build your appointment in four steps",
      reset: "Clear selections",
      step1Loading: "Loading services...",
      step1DescriptionFallback: "Classic grooming service.",
      step1Selected: "Selected",
      step1Choose: "Choose service",
      step2Loading: "Loading barbers...",
      step2Fallback: "Experienced barber focused on precision and comfort.",
      step2Selected: "Selected",
      step2Choose: "Choose barber",
      dateLabel: "Date",
      slotsTitle: "Available slots",
      slotsDescription: "We show slots based on the service duration and the barber schedule.",
      slotsLoading: "Loading available times...",
      slotsEmpty:
        "No slots are available for the selected date. If you picked today, working hours may already be over.",
      contactTitle: "Contact details",
      contactDescription:
        "Add your Telegram username too, and the bot can send reminders and booking updates.",
      placeholderName: "Your name",
      placeholderPhone: "Phone number",
      placeholderTelegram: "Telegram username, for example @yourname",
      placeholderNotes: "Optional notes",
      telegramHint:
        "Start the Telegram bot first, then you can later use commands to manage your bookings there.",
      managementHint:
        "After payment, you will receive a personal link for rescheduling or canceling the appointment.",
      invalidTelegram: "Use a valid Telegram username",
      submit: "Continue to payment",
      submitting: "Reserving your slot...",
      submitError: "Unable to reserve this slot. Try another time slot.",
    },
    checkout: {
      badge: "Booking payment",
      loading: "Preparing checkout...",
      notFound: "Booking hold not found.",
      title: "Finish the deposit to confirm the booking",
      description:
        "Your selected slot is held for a short time. Once payment succeeds, the appointment will be confirmed automatically.",
      expiresAt: "Hold expires at",
      status: "Hold status",
      paymentStatus: "Payment status",
      depositLabel: "Due now",
      totalLabel: "Full service price",
      mockNote:
        "This build uses a mock payment flow: the button below simulates a successful provider payment and runs the same webhook confirmation path.",
      preparing: "Creating checkout session...",
      checkoutError: "We could not prepare the payment. Please try again.",
      paymentError: "We could not finish the payment.",
      processing: "Processing payment...",
      payAction: "Pay deposit",
      retryPayment: "Prepare payment again",
      retry: "Choose another slot",
      expiredTitle: "The hold has expired",
      expiredText: "The slot is no longer reserved. Pick another time and create a new hold.",
      nextLabel: "What happens next",
      nextTitle: "We confirm the visit only after the webhook succeeds",
      nextText:
        "This page will redirect to the final confirmation as soon as the webhook finishes processing the payment.",
      stepOne: "1. The backend creates a short-lived booking hold and checkout session.",
      stepTwo: "2. After successful payment, the webhook records the payment event.",
      stepThree: "3. Only then is the final booking created with your personal access token.",
    },
    account: {
      badge: "My booking",
      title: "Client cabinet",
      description:
        "Open your recent bookings here or access an appointment manually with the booking id and personal token.",
      recent: "Recent bookings",
      noRecent: "No saved bookings yet. Once you create one, it will appear here automatically.",
      openBooking: "Open booking",
      removeBooking: "Remove",
      manualTitle: "Open with booking details",
      manualDescription:
        "Paste the booking id and the personal token from the confirmation page or message.",
      bookingId: "Booking id",
      token: "Personal token",
      open: "Open cabinet",
      helper:
        "After opening the appointment, you will be able to reschedule or cancel it while it is still active.",
    },
    confirmation: {
      loading: "Loading booking...",
      incompleteTitle: "Booking link is incomplete",
      incompleteText:
        "Open the full confirmation link from the booking page or ask the shop to resend your access link.",
      backHome: "Back to home",
      notFound: "Booking not found.",
      accessLabel: "Booking access",
      title: "Your appointment details",
      status: "Status",
      client: "Client",
      phone: "Phone",
      barber: "Barber",
      service: "Service",
      start: "Start",
      end: "End",
      created: "Created",
      justNow: "just now",
      cancelReason: "Cancellation reason",
      call: "Call the shop",
      portal: "Open cabinet",
      selfServiceLabel: "Self-service",
      selfServiceTitle: "Move or cancel the appointment",
      selfServiceText:
        "This personal access keeps the same barber and service. It only changes the time slot.",
      cancelTitle: "Cancel booking",
      cancelPlaceholder: "Optional reason",
      cancelError: "We could not cancel this booking right now.",
      cancelPending: "Canceling...",
      cancelAction: "Cancel appointment",
      rescheduleTitle: "Reschedule booking",
      slotsLoading: "Loading slots...",
      slotsEmpty: "No alternative slots for the selected date.",
      rescheduleError: "We could not move the booking to that slot.",
      reschedulePending: "Saving...",
      rescheduleAction: "Confirm new time",
      closedText: "This appointment is already closed for self-service changes.",
      contactsLabel: "Contacts",
      telegram: "Open Telegram",
      accountSaved: "Access to this booking has been saved in your cabinet.",
    },
    status: {
      pending: "Pending",
      confirmed: "Confirmed",
      canceled: "Canceled",
      completed: "Completed",
    },
    holdStatus: {
      created: "Created",
      payment_pending: "Waiting for payment",
      paid: "Paid, confirming",
      converted: "Confirmed",
      expired: "Hold expired",
      released: "Released",
      failed: "Payment failed",
    },
    paymentStatus: {
      unpaid: "Unpaid",
      partially_paid: "Partially paid",
      pending: "Pending",
      paid: "Paid",
      failed: "Failed",
      refunded: "Refunded",
      partial_refund: "Partial refund",
    },
    shop: {
      city: "Kyiv",
      hours: [
        { label: "Mon-Fri", value: "09:00-20:00" },
        { label: "Sat", value: "10:00-18:00" },
        { label: "Sun", value: "By schedule only" },
      ],
      highlights: [
        "Real-time slots based on barber schedules and service duration",
        "Quick guest booking with optional Telegram reminders",
        "Fast reschedule or cancel access from the client cabinet",
      ],
      policies: [
        "Free reschedule or cancel up to 2 hours before the visit.",
        "If you are running late, message us in Telegram and we will try to hold the chair.",
        "For beard and combo services, please arrive 5 minutes early.",
      ],
      faq: [
        {
          question: "Can I book without registration?",
          answer: "Yes. Name and phone are enough, and Telegram is optional for reminders.",
        },
        {
          question: "How do reminders work?",
          answer: "If you add your Telegram username and start our bot, we can send booking updates and reminders there.",
        },
        {
          question: "Can I switch barber later?",
          answer: "The client cabinet keeps the same barber and service. For bigger changes, contact the shop directly.",
        },
      ],
    },
  },
} as const;

export function getContent(language: AppLanguage) {
  return content[language];
}
